sudo: required
language: csharp
mono: none
matrix:
  include:
    - os: linux    
      dotnet: 2.1
    - os: osx
      dotnet: 2.1.300
script:
 - dotnet publish
 - dotnet test NetcoreReact.IntegrationTests 
 - dotnet test NetcoreReact.NUnitTests 