version: '1.0.{build}'
image: Visual Studio 2017
branches:
  only:
  - master
init:
install:
  # Install repo specific stuff here
before_build:
  # Display .NET Core version
  - cmd: dotnet --version
build_script:
  - cmd: dotnet publish ./NetcoreReact/NetcoreReact.csproj
after_build:
  # For once the build has completed
artifacts:
clone_depth: 1
test_script:
  - cmd: dotnet test NetCoreReactReduxAdvanced.IntegrationTest
  - cmd: dotnet test NetcoreReact.NUnitTests
on_finish :
  # any cleanup in here
deploy: off